# Generated by Django 4.2.7 on 2023-11-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
